### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by timdorr** [rackt/rackt-codemod#6]
The purpose of each codemod is pretty opaque, so we can both test the modification and get some built-in examples if we're able to build out a test suite.

**Comment by taion** [comment]
Yup - @cpojer was on my case about this as well. We should take the scaffolding from his codemod repos, then use the changes to our tests as fixtures.

**Comment by joshblack** [comment]
I've had success running tests with the following structure: https://github.com/joshblack/codemods/tree/master/test just adding in folders for tests as developers make issues on the repo. Any thoughts? Would love to help contribute to this repo and adding tests seems like a good start.

**Comment by timdorr** [comment]
@joshblack Yeah, definitely! If you want to open a PR, that would be super duper helpful.

**Comment by cpojer** [comment]
The setup from https://github.com/reactjs/react-codemod can literally be copy and pasted. A bunch of other forks use the same structure, it would be nice to keep some sort of consistency.

**Comment by joshblack** [comment]
Sounds good, consistency is important.

**Comment by joshblack** [comment]
Do we have example project files that the mods were ran against that I can start filling the test cases out with?

**Comment by taion** [comment]
@joshblack The tests and examples on history and React Router, actually.

**Comment by joshblack** [comment]
Perfect, thanks for the heads up!

**Comment by joshblack** [comment]
Just wanted to give an update, currently working on this here: https://github.com/joshblack/rackt-codemod just have to add the history tests and I'll open up a PR.

**Comment by cpojer** [comment]
Awesome!
